<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>buoi6.ex2_baitapmang2</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Include="ex1.-mang.cs" />
  </ItemGroup>

</Project>
